### ISSUE TITLE
Allow running just the suite of tests

### ISSUE THREAD

**Issue by SimonRichardson** [babakks/vscode-go-test-suite#13]
Gocheck allows you to specify a filter (`-check.f`) using regex when running the tests. I normally use it to run just a suite of tests.

We could in theory see the following pattern `var _ = gc.Suite(&suite{})` with the regex `^var\s_\s=\s.*\.Suite\(&.*\{\}\)` and add the ability to run just the suite with a filter.

```
import (
    gc "gopkg.in/check.v1"
)

type suite struct{}

var _ = gc.Suite(&suite{})

func (*suite) TestMe(c *gc.C) {
}

func (*suite) TestEverythingElse(c *gc.C) {
}

```

**Comment by babakks** [comment]
@SimonRichardson Thanks for the feedback.

It's a bit tricky to look for the suite registrations. For example, what if they do it inside a root `Test` function? I know, it's not required to support all possible cases, but still if we could do it in a more independent way it'd be better.

At the moment I can think of two solutions:

1. In the *Testing* sidebar, the tests are organized in this way: parent(s) >> file >> test function (screenshot below). My suggestion is we can add the new **suite** level between file and test functions so that when you click on it an entire test suite runs.
   ![sidebar-organization](https://github.com/babakks/vscode-go-test-suite/assets/36728931/1380a646-0d65-46ce-9db0-6e9f053e4c4c)

2. We can add two new code lens commands, `Run Suite` and `Debug Suite`, to the existing code lenses (screenshot below), so that the user can easily run a suite without having to open the sidebar.
   ![code-lenses](https://github.com/babakks/vscode-go-test-suite/assets/36728931/0ff0c2a9-e10b-4b23-960f-81da9b447bd5)


Actually, both of these two features can be added to the extension.

What do you think?

**Comment by SimonRichardson** [comment]
Yeah, that's a start. I'd +1 on this change.

**Comment by babakks** [comment]
@SimonRichardson I just published a new release which implements the first suggestion of the above. The second suggestion could be a bit tricky to implement due to some shortcomings in VS Code testing API (the code lenses are already working with a small hack). Anyway, I might try I the near future to implement the second option as well.

Could you please upgrade to v0.0.12 and let me know if things work as expected?
